# Generated by Django 3.2.7 on 2023-12-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231228_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Delhi', max_length=180, verbose_name='City'),
        ),
    ]
